// Code generated by sqlc. DO NOT EDIT.

package genDB

import (
	"database/sql"
	"time"
)

type Apartment struct {
	ApartmentID  int32          `json:"apartment_id"`
	Name         string         `json:"name"`
	FullAddress  string         `json:"full_address"`
	Street       string         `json:"street"`
	City         string         `json:"city"`
	State        string         `json:"state"`
	ZipCode      int32          `json:"zip_code"`
	Neighborhood string         `json:"neighborhood"`
	Unit         sql.NullString `json:"unit"`
	Lat          float64        `json:"lat"`
	Lng          float64        `json:"lng"`
	Rent         int32          `json:"rent"`
	Sqft         sql.NullInt32  `json:"sqft"`
	Beds         int32          `json:"beds"`
	Baths        int32          `json:"baths"`
	AvailableOn  time.Time      `json:"available_on"`
	CreatedAt    time.Time      `json:"created_at"`
	DaysOnMarket sql.NullInt32  `json:"days_on_market"`
	Description  sql.NullString `json:"description"`
	Amenities    []string       `json:"amenities"`
	UploadIds    []string       `json:"upload_ids"`
	IsArchived   bool           `json:"is_archived"`
	BuildingID   int32          `json:"building_id"`
	RealtorID    int32          `json:"realtor_id"`
}

type Building struct {
	BuildingID   int32          `json:"building_id"`
	Name         string         `json:"name"`
	FullAddress  string         `json:"full_address"`
	Street       string         `json:"street"`
	City         string         `json:"city"`
	State        string         `json:"state"`
	ZipCode      int32          `json:"zip_code"`
	Neighborhood string         `json:"neighborhood"`
	Lat          float64        `json:"lat"`
	Lng          float64        `json:"lng"`
	Description  sql.NullString `json:"description"`
	Amenities    []string       `json:"amenities"`
	UploadIds    []string       `json:"upload_ids"`
	OwnerID      int32          `json:"owner_id"`
	CreatedAt    time.Time      `json:"created_at"`
}

type Owner struct {
	OwnerID     int32          `json:"owner_id"`
	UserID      string         `json:"user_id"`
	Name        string         `json:"name"`
	Email       sql.NullString `json:"email"`
	PhoneNumber sql.NullString `json:"phone_number"`
	Company     sql.NullString `json:"company"`
	CreatedAt   time.Time      `json:"created_at"`
}

type Realtor struct {
	RealtorID   int32          `json:"realtor_id"`
	UserID      string         `json:"user_id"`
	Name        string         `json:"name"`
	Email       sql.NullString `json:"email"`
	PhoneNumber sql.NullString `json:"phone_number"`
	Company     sql.NullString `json:"company"`
	CreatedAt   time.Time      `json:"created_at"`
}
